runtime: python
env: flex
entrypoint: waitress-serve --port=$PORT server:app
instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.65